server:
  port: 8084

spring:
  cloud:
    gateway:
      server: # This is the new level
        webflux: # This is the new level
          routes:
            - id: product_service_route
              uri: http://localhost:8082
              predicates:
                - Path=/api/products/**
            - id: order_service_route
              uri: http://localhost:8083
              predicates:
                - Path=/api/orders/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "http://localhost:3000"
                allowedMethods:
                  - GET
                  - POST
                  - PUT
                  - PATCH
                  - DELETE
                allowedHeaders: "*"